# -*- coding: utf-8 -*-
"""
Extrae las cookies de YouTube desde el perfil Edge persistente
(`~/.notebooklm/browser_profile_edge`) usando Playwright y las guarda
en formato Netscape (cookies.txt) listo para `yt-dlp --cookies`.

Esto resuelve el bug del SQLite locked: en lugar de leer la base de
datos de Edge mientras Edge está corriendo, Playwright abre el perfil
en una instancia separada y exporta las cookies via API.

Salida:
  E:\\vars\\var 5\\YouTube-jjmobijuesa\\cookies.txt
"""
import sys
import time
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

from playwright.sync_api import sync_playwright

PROFILE = Path.home() / ".notebooklm" / "browser_profile_edge"
OUT = Path(r"E:\vars\var 5\YouTube-jjmobijuesa\cookies.txt")


def to_netscape(cookies):
    """Convierte la lista de cookies de Playwright al formato Netscape."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by harvest_cookies.py via Playwright/Edge",
        f"# {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        # incluir dominio aunque no empiece por punto
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires") or 0)
        if expires <= 0:
            expires = int(time.time()) + 365 * 24 * 3600
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([
            domain, include_subdomains, path, secure, str(expires), name, value
        ]))
    return "\n".join(lines) + "\n"


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    print(f"Profile: {PROFILE}")
    if not PROFILE.exists():
        print("ERROR: perfil Edge no existe; usar NotebookLM al menos una vez.")
        sys.exit(2)

    with sync_playwright() as p:
        ctx = p.chromium.launch_persistent_context(
            user_data_dir=str(PROFILE),
            channel="msedge",
            headless=True,
            args=["--disable-blink-features=AutomationControlled"],
        )
        # Visitar YouTube para asegurar que las cookies estén cargadas
        page = ctx.new_page()
        page.goto("https://www.youtube.com/", wait_until="domcontentloaded")
        page.wait_for_timeout(3000)
        cookies = ctx.cookies()
        # filtrar a dominios relevantes
        keep = [c for c in cookies
                if any(d in c.get("domain", "") for d in
                       ["youtube.com", "google.com", ".google.com"])]
        OUT.write_text(to_netscape(keep), encoding="utf-8")
        print(f"Cookies guardadas: {len(keep)} de {len(cookies)} totales")
        print(f"Archivo: {OUT}")

        # Verificación de login: ¿hay SID en las cookies de .google.com?
        sid = next((c for c in keep if c["name"] == "SID"
                    and ".google.com" in c["domain"]), None)
        if sid:
            print(f"Sesión Google detectada (SID presente).")
        else:
            print("ADVERTENCIA: no se detectó cookie SID — sesión Google puede no estar.")
        ctx.close()


if __name__ == "__main__":
    main()
